name: Setup CI environment
description: Use this composite action to setup a proper Docker environment with Tutor
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# jobs:
#    my-job:
#      steps:
#        - uses: overhangio/test-docker-build@main

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip setuptools==44.0.0 wheel
    - name: Install dependencies
      shell: bash
      run: pip install 'tutor[full]'
    - name: Configure environment
      shell: bash
      run: tutor plugins enable mfe && tutor config save
